//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario_alerta
    {
        public int IdFormulario { get; set; }
        public int IdAlerta { get; set; }
        public Nullable<int> FkIdEmpleado { get; set; }
        public Nullable<System.DateTime> FechaAlerta { get; set; }
    
        public virtual alerta alerta { get; set; }
        public virtual formulario formulario { get; set; }
    }
}
