//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tramite_proceso
    {
        public int IdTramite { get; set; }
        public int IdEtapaTramite { get; set; }
        public int FkIdEmpleado { get; set; }
        public Nullable<sbyte> EstadoActual { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual etapatramite etapatramite { get; set; }
        public virtual tramite tramite { get; set; }
    }
}
