//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiRegistro.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string user {
            get {
                return ((string)(this["user"]));
            }
            set {
                this["user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pass {
            get {
                return ((string)(this["pass"]));
            }
            set {
                this["pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool termsandconditions {
            get {
                return ((bool)(this["termsandconditions"]));
            }
            set {
                this["termsandconditions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Para cargar un nuevo formulario diríjase a la sección de formularios, en donde, p" +
            "odrá manipular las diversas clases de formularios con su numeración y stock inde" +
            "pendientes de cada formulario.")]
        public string slide2 {
            get {
                return ((string)(this["slide2"]));
            }
            set {
                this["slide2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Para cargar un nuevo tramite ingresar en tramites y luego hacer click en ingresar" +
            " nuevo tramite la cual lo guiara mediante una serie de pasos a seguir colocando " +
            "la informacion correspondiente al tramite.")]
        public string slide1 {
            get {
                return ((string)(this["slide1"]));
            }
            set {
                this["slide1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Para generar estadísticas diríjase a la sección de estadística, en donde, podrá m" +
            "anipular la información, generar informes, generar gráficos, comparar datos, exp" +
            "ortar documentos pdf y llevar un control de su registro de una forma muy intuiti" +
            "va.")]
        public string slide3 {
            get {
                return ((string)(this["slide3"]));
            }
            set {
                this["slide3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Añadir tramites")]
        public string slidetittle1 {
            get {
                return ((string)(this["slidetittle1"]));
            }
            set {
                this["slidetittle1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Añadir formularios")]
        public string slidetittle2 {
            get {
                return ((string)(this["slidetittle2"]));
            }
            set {
                this["slidetittle2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gestionar estadisticas")]
        public string slidetittle3 {
            get {
                return ((string)(this["slidetittle3"]));
            }
            set {
                this["slidetittle3"] = value;
            }
        }
    }
}
