//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public formulario()
        {
            this.formulario_alerta = new HashSet<formulario_alerta>();
            this.numeracionformulario = new HashSet<numeracionformulario>();
            this.formulario_parametro = new HashSet<formulario_parametro>();
        }
    
        public int IdFormulario { get; set; }
        public int FkIdEmpresa { get; set; }
        public int FkIdTipo { get; set; }
        public Nullable<System.DateTime> UltimaActualizacion { get; set; }
        public Nullable<sbyte> Alerta { get; set; }
    
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formulario_alerta> formulario_alerta { get; set; }
        public virtual tipoformulario tipoformulario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<numeracionformulario> numeracionformulario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formulario_parametro> formulario_parametro { get; set; }
    }
}
