//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.empleado = new HashSet<empleado>();
            this.usuario_rol = new HashSet<usuario_rol>();
        }
    
        public int IdUsuario { get; set; }
        public int FkIdPerfil { get; set; }
        public Nullable<int> FkIdSeguridad { get; set; }
        public string Usuario1 { get; set; }
        public string Contraseña { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> UltimoAcceso { get; set; }
        public Nullable<sbyte> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual perfil perfil { get; set; }
        public virtual usuario_seguridad usuario_seguridad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_rol> usuario_rol { get; set; }
    }
}
